title: Blog on DevOps, Kubernetes, CI/CD from Vladyslav Didenko
description: > # this means to ignore newlines until "baseurl:"
  This is my almost secret space to share what I've learned. Things that matte
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nodevops.nl" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Vlad Didenko # add your name
author-img: vlad-d-profile.jpeg # add your photo
about-author: I am DevOps focusing on AWS, Serverless, IAC, CI/CD , Docker, Kubernetes and . Always hungry to keep learning. # add description
social-twitter: NodevopsN # add your Twitter handle
social-facebook: NodevopsN # add your Facebook handle
social-github: NodevopsN # add your Github handle
social-linkedin: NodevopsN # add your Linkedin handle


# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
# https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/installation.md
  - jekyll-seo-tag
# https://github.com/jekyll/jekyll-sitemap
  - jekyll-sitemap
paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
